--drop tables
DROP TABLE files;
DROP TABLE word_counts;

-- create table with text data
CREATE TABLE files(lines STRING);

--load text data into the table
LOAD DATA LOCAL INPATH '/root/input.txt' INTO TABLE files;
 
-- Create a new table using data from the files table
CREATE TABLE word_counts AS
SELECT word, count(1) AS count FROM
(SELECT explode(split(lines, ' ')) AS word FROM files) w
GROUP BY word
ORDER BY word;

-- view word_counts table
SELECT * FROM word_counts;
